# dockerfiles/Dockerfile.frontend
FROM node:18-alpine as build
WORKDIR /app
COPY ./futurowork-frontend /app
RUN npm install --silent && npm run build

FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
